<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>contexts</key>
	<dict>
		<key>import</key>
		<array>
			<dict>
				<key>match</key>
				<string>".+"</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>string.uhm</string>
			</dict>
		</array>
		<key>info</key>
		<array>
			<dict>
				<key>match</key>
				<string>".+"</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>string.uhm</string>
			</dict>
		</array>
		<key>main</key>
		<array>
			<dict>
				<key>match</key>
				<string>//.+</string>
				<key>scope</key>
				<string>comment.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>'</string>
				<key>scope</key>
				<string>invalid.illegal.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^Info\s</string>
				<key>push</key>
				<string>info</string>
				<key>scope</key>
				<string>storage.type.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^Import\s</string>
				<key>push</key>
				<string>import</string>
				<key>scope</key>
				<string>storage.type.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(Wave|Spectrum|Phase|Seed|Interpolate|Normalize|NumFrames|Envelope|Import|Move)\b</string>
				<key>scope</key>
				<string>storage.type.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)\b(start|end|to|from|direction|lowest|highest|curve|type|target|blend|base|db|metric|snippets|threshold|weighting)\b</string>
				<key>scope</key>
				<string>variable.parameter.function-call.uhm markup.italic.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(L[0-8])\b|\b(T[0-8])\b</string>
				<key>scope</key>
				<string>variable.parameter.function-call.uhm markup.italic.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(replace|add|sub|multiply|multiplyAbs|divide|divideAbs|min|max|all|each|quadric|linear|exponential|peak|rms|average|ptp|morph1|morph2|switch|crossfade|spectrum|zerophase|forward|fwd|backward)\b</string>
				<key>scope</key>
				<string>text.uhm markup.italic.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(rand|randf|rands)\b</string>
				<key>scope</key>
				<string>text.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(e|pi)\b</string>
				<key>scope</key>
				<string>text.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(phase|table|index|frame)\b</string>
				<key>scope</key>
				<string>text.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(x|y)\b</string>
				<key>scope</key>
				<string>text.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b([0-9]+)\b</string>
				<key>scope</key>
				<string>text.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>"</string>
				<key>scope</key>
				<string>punctuation.definition.arguments.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\(|\)</string>
				<key>scope</key>
				<string>punctuation.separator.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>,</string>
				<key>scope</key>
				<string>punctuation.separator.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(acos|asin|atan|atan2|cos|cosh|sin|sinh|tan|tanh|abs|ceil|floor|frac|round|select|exp|fac|ln|log10|pow|sqrt|lin_db|db_lin)\b</string>
				<key>scope</key>
				<string>support.function.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(env|lowpass|bandpass|highpass|main_fi|main_fp|aux1_fi|aux1_fp|aux2_fi|aux2_fp)\b</string>
				<key>scope</key>
				<string>support.function.builtin.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(aux1|aux2|main)\b</string>
				<key>scope</key>
				<string>text.uhm markup.bold.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\+|\-|\*|\/|%|\^|\&lt;|\&gt;|!</string>
				<key>scope</key>
				<string>keyword.operator.uhm</string>
			</dict>
			<dict>
				<key>match</key>
				<string>=</string>
				<key>scope</key>
				<string>keyword.operator.assignment.uhm</string>
			</dict>
		</array>
	</dict>
	<key>file_extensions</key>
	<string>uhm</string>
	<key>name</key>
	<string>UHM</string>
	<key>scope</key>
	<string>source.uhm</string>
</dict>
</plist>
